"""Back up local state that cannot be regenerated by rerunning something.

Two things qualify, and this script archives both:

- `secrets/ebay_chrome_profile/`: the agent's eBay login session. Recreating it
  means a manual, interactive eBay sign-in through
  `scratch_ebay_browser_login.py`, complete with whatever 2FA or captcha eBay
  decides to serve that day.
- `scraperagent.db` (`config.DB_PATH`): negotiation transcripts, seller
  replies, offer history, and per-search cost records. The database file
  itself recreates on boot with an empty schema, but its *contents* do not —
  they are gitignored and, unlike the Chrome profile, were previously not
  backed up anywhere. A run of the app can wipe them (as happened once
  already); this archive is the only recovery path.

Everything else in the app is disposable: tokens refetch, listings re-search.

Usage:
    python -m scripts.backup_profile                 # defaults from config
    python -m scripts.backup_profile --keep 10
    python -m scripts.backup_profile --backup-dir D:/Backups/ScraperAgent

Scheduling on Windows (see README for the full Task Scheduler recipe):
    schtasks /create /tn "ScraperAgent profile backup" /sc weekly ...
"""

from __future__ import annotations

import argparse
import logging
import sys
import zipfile
from datetime import datetime
from pathlib import Path

import config


log = logging.getLogger(__name__)

# Archives are matched by this prefix for retention. Anything else in the backup
# directory is left alone — the directory may well be a general-purpose folder,
# and a retention policy that deletes files it didn't create is a footgun.
ARCHIVE_PREFIX = "ebay_chrome_profile-"
ARCHIVE_GLOB = f"{ARCHIVE_PREFIX}*.zip"

# Name the database is stored under inside the archive. Kept distinct from any
# path under the profile directory so the two can never collide.
DB_ARCNAME = "scraperagent.db"


class BackupError(RuntimeError):
    """Raised when the profile can't be backed up."""


def backup_profile(
    profile_dir: Path,
    backup_dir: Path,
    *,
    keep: int = 5,
    now: datetime | None = None,
    db_path: Path | None = None,
) -> Path:
    """Zip `profile_dir` (and, if given, `db_path`) into a timestamped archive
    under `backup_dir`.

    Returns the path to the archive it wrote. Prunes older archives to `keep`
    afterwards, so a scheduled run is a complete backup cycle.

    `db_path` is optional so callers that only care about the Chrome profile
    (and the existing test suite) don't have to pass one. A missing or
    zero-length database is not an error here — a fresh install legitimately
    has neither yet — it's logged as a warning and the archive is produced
    without it.
    """
    profile_dir = Path(profile_dir)
    backup_dir = Path(backup_dir)

    if not profile_dir.is_dir():
        raise BackupError(
            f"Chrome profile directory does not exist: {profile_dir}. "
            "Run `python scratch_ebay_browser_login.py` to create it."
        )

    members = [p for p in profile_dir.rglob("*") if p.is_file()]
    if not members:
        # An empty archive would look like a successful backup, and as the
        # retention window rolls forward it would quietly evict the real ones.
        raise BackupError(f"Chrome profile directory is empty: {profile_dir}")

    stamp = (now or datetime.now()).strftime("%Y%m%d-%H%M%S")
    backup_dir.mkdir(parents=True, exist_ok=True)
    archive = backup_dir / f"{ARCHIVE_PREFIX}{stamp}.zip"

    skipped = 0
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for member in members:
            try:
                zf.write(member, arcname=str(member.relative_to(profile_dir)))
            except (PermissionError, OSError) as exc:
                # Chrome keeps an exclusive lock on parts of a live profile on
                # Windows. Aborting here would mean the backup only ever
                # succeeds while the browser is closed — which is precisely not
                # when a scheduled task runs. The session-bearing files (cookies,
                # Local State) are readable in practice; losing a lock file or a
                # cache shard costs nothing.
                log.warning("skipping unreadable file %s: %s", member, exc)
                skipped += 1

        db_included = False
        if db_path is not None:
            db_path = Path(db_path)
            if not db_path.is_file():
                log.warning(
                    "database not found, skipping: %s (fine on a fresh install)",
                    db_path,
                )
            elif db_path.stat().st_size == 0:
                log.warning(
                    "database is zero-length, skipping: %s (fine on a fresh install, "
                    "but check this if the app has been running)",
                    db_path,
                )
            else:
                try:
                    zf.write(db_path, arcname=DB_ARCNAME)
                    db_included = True
                except (PermissionError, OSError) as exc:
                    # SQLite doesn't hold an exclusive lock on Windows the way
                    # Chrome does, but the app may have a connection open. Warn
                    # and keep going rather than losing the profile backup too.
                    log.warning("skipping unreadable database %s: %s", db_path, exc)

    log.info(
        "backed up %d profile files (%d skipped), database %sincluded, to %s (%.1f MB)",
        len(members) - skipped, skipped, "" if db_included else "not ",
        archive, archive.stat().st_size / 1_048_576,
    )
    prune_backups(backup_dir, keep=keep)
    return archive


def prune_backups(backup_dir: Path, *, keep: int) -> list[Path]:
    """Delete all but the `keep` newest archives. Returns what it deleted.

    Ordering is by filename, not mtime: the timestamp is baked into the name, so
    a lexicographic sort is chronological and survives a copy that resets mtimes.
    """
    backup_dir = Path(backup_dir)
    if keep < 1:
        raise BackupError(f"keep must be at least 1, got {keep}")

    archives = sorted(backup_dir.glob(ARCHIVE_GLOB))
    doomed = archives[:-keep] if len(archives) > keep else []
    for path in doomed:
        log.info("pruning old backup %s", path.name)
        path.unlink()
    return doomed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--profile-dir", type=Path, default=config.EBAY_BROWSER_PROFILE_DIR)
    parser.add_argument("--backup-dir", type=Path, default=config.BACKUP_DIR)
    parser.add_argument("--keep", type=int, default=config.BACKUP_KEEP)
    parser.add_argument("--db-path", type=Path, default=config.DB_PATH)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    try:
        archive = backup_profile(args.profile_dir, args.backup_dir, keep=args.keep, db_path=args.db_path)
    except BackupError as exc:
        # Non-zero exit so Task Scheduler shows the run as failed rather than
        # reporting success on a backup that never happened.
        log.error("%s", exc)
        return 1
    print(archive)
    return 0


if __name__ == "__main__":
    sys.exit(main())
